Add option to run docker commands with sudo and protect certain environment variables
jenkinsci/docker-custom-build-environment-plugin pull request #62
Opened 2016-11-17 22:20 UTC by Tyler-Yates

Adds two new options to the plugin under the "Advanced" section:
* A checkbox to run the docker commands with sudo
* A text-box where the user can enter a comma-separated list of environment variables to protect, keeping them from being overwritten with the values from the host machine

The sudo option is enabled by default.
PATH is the only protected environment variable by default.

2016-12-27 10:41 UTC, rdsubhas commented
Would love to see this merged, thanks!

2016-12-27 13:12 UTC, oleg-nenashev requested changes
IMHO needs a fix due to the binary compatibility issues and lack of input field verification

2016-12-27 13:12 UTC, oleg-nenashev commented on src/main/java/com/cloudbees/jenkins/plugins/docker_build_env/Docker.java
> +    public Docker(DockerServerEndpoint dockerHost, String dockerInstallation, String credentialsId, AbstractBuild build, Launcher launcher, TaskListener listener, boolean verbose, boolean privileged,
🐛 This change breaks the binary compatibility of the non-restricted constructor

2016-12-27 13:12 UTC, oleg-nenashev commented on src/main/java/com/cloudbees/jenkins/plugins/docker_build_env/Docker.java
> +                this.protectedEnvironmentVariables.add(variable.trim());
There is a risk of getting empty strings here. IMHO blank strings should be skipped in this cycle

2016-12-27 13:12 UTC, oleg-nenashev commented on src/main/java/com/cloudbees/jenkins/plugins/docker_build_env/Docker.java
> +            if ("HOSTNAME".equals(e.getKey()) || protectedEnvironmentVariables.contains(e.getKey())) {
Makes sense to ensure this class is being never persisted to the disk and deserialized. Otherwise there may be null

2016-12-27 13:12 UTC, oleg-nenashev commented on src/main/java/com/cloudbees/jenkins/plugins/docker_build_env/Docker.java
> +        if(sudo) {
Would be nice to generalize the code a bit to follow the DRY principle. Maybe a utility method?

2016-12-27 13:12 UTC, oleg-nenashev commented on src/main/java/com/cloudbees/jenkins/plugins/docker_build_env/DockerBuildWrapper.java
> +                              String net, String memory, String cpu, boolean sudo, String protectedEnvironmentVariables) {
Binary compat issue 🐛

2016-12-27 13:12 UTC, oleg-nenashev commented on src/main/java/com/cloudbees/jenkins/plugins/docker_build_env/DockerBuildWrapper.java
> +    public String getProtectedEnvironmentVariables() {
Add CheckForNull. Even if null is not being passed from UI, this field will be null when the build wrapper is being loaded from the disk for existing jobs. 🐛

2016-12-27 13:12 UTC, oleg-nenashev commented on src/main/resources/com/cloudbees/jenkins/plugins/docker_build_env/DockerBuildWrapper/help-protectedEnvironmentVariables.html
> +</div>
Good practice: add line breaks at the end

2016-12-27 21:22 UTC, Tyler-Yates commented on src/main/java/com/cloudbees/jenkins/plugins/docker_build_env/Docker.java
> +    public Docker(DockerServerEndpoint dockerHost, String dockerInstallation, String credentialsId, AbstractBuild build, Launcher launcher, TaskListener listener, boolean verbose, boolean privileged,
I'll change this by adding a new constructor with the additional parameters.

2016-12-27 21:23 UTC, Tyler-Yates commented on src/main/java/com/cloudbees/jenkins/plugins/docker_build_env/Docker.java
> +            if ("HOSTNAME".equals(e.getKey()) || protectedEnvironmentVariables.contains(e.getKey())) {
Are you recommending that I add a check here to ensure protectedEnvironmentVariables is not null?

2016-12-27 21:32 UTC, Tyler-Yates commented on src/main/resources/com/cloudbees/jenkins/plugins/docker_build_env/DockerBuildWrapper/help-protectedEnvironmentVariables.html
> +</div>
exposeDocker.html, dockerRegistryCredentials.html, dockerHost, and help.html do not have line breaks at the end either but I won't change those files in this PR

2016-12-27 21:48 UTC, Tyler-Yates reviewed
Commit addressing PR comments has been pushed

2016-12-29 14:08 UTC, rdsubhas commented
thank you so much 👍

2017-01-03 12:50 UTC, rdsubhas commented
@oleg-nenashev sorry but a gentle ping to check this out 😄

2017-01-23 17:38 UTC, Tyler-Yates commented
@oleg-nenashev  I have addressed your PR comments.

2017-02-01 12:01 UTC, rdsubhas commented
@oleg-nenashev @Tyler-Yates Sorry gentle ping :) This feature would be awesome to have, any plans of getting this merged?

2017-02-01 17:27 UTC, Tyler-Yates commented
I am ready to address any further code review comments so getting this merged is a matter of waiting for @oleg-nenashev.

2017-02-09 19:08 UTC, rdsubhas commented
@oleg-nenashev really sorry to keep pinging, but the PATH protection is becoming a big blocker, can you please close this :)

2017-06-01 21:22 UTC, Tyler-Yates commented
@oleg-nenashev any update on this?

2017-06-01 21:29 UTC, oleg-nenashev commented
Sorry for the missing response. This plugin is not in my priority watch list, and I have missed all previous pings since I was really busy this winter. I am not the plugin maintainer anyway, hence my feedback was not a blocker. Not sure who is the current maintainer though.

The critical comments have been addressed,

2017-06-01 21:29 UTC, oleg-nenashev approved these changes

2017-06-01 22:50 UTC, Tyler-Yates commented
@ndeloof can you merge this?

2017-06-02 05:12 UTC, ndeloof commented
@Tyler-Yates I'm not maintaining this plugin anymore

2017-06-02 20:02 UTC, Tyler-Yates commented
@ndeloof do you know who is the current maintainer? You mere the last person to accept a merge to this project.

2017-06-03 07:31 UTC, ndeloof commented
it's looking for adoption, see https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Docker+Custom+Build+Environment+Plugin

2017-06-03 15:43 UTC, Tyler-Yates commented
I have sent out a request to become a maintainer for this plugin. I have CC'ed @oleg-nenashev and @ndeloof.

2018-04-06 05:58 UTC, ofersadgat commented
@ndeloof @Tyler-Yates can we sort out the maintainer for this? I love the functionality provided by this plugin, but as docker continues evolving, I think that issues are starting to pop up with noone to fix them.

2018-04-06 11:35 UTC, jonhermansen commented
@ofersadgat I am the current maintainer. I will take a look at these changes over the weekend

2025-04-07 04:56 UTC, closed without merging